"""special missions

Revision ID: 0c4444c27700
Revises: 8bbc48ab5173
Create Date: 2025-07-22 16:15:20.000979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c4444c27700'
down_revision: Union[str, Sequence[str], None] = '8bbc48ab5173'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('special_missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('cost', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('my_special_missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['special_missions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('professions', sa.Column('unlock_mission_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'professions', 'special_missions', ['unlock_mission_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'professions', type_='foreignkey')
    op.drop_column('professions', 'unlock_mission_id')
    op.drop_table('my_special_missions')
    op.drop_table('special_missions')
    # ### end Alembic commands ###
