"""Add user auth and user saved buildings/professions

Revision ID: 1eb43b76aaec
Revises: 
Create Date: 2025-07-16 13:02:01.511808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb43b76aaec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('my_buildings', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'my_buildings', 'users', ['user_id'], ['id'])
    op.add_column('my_professions', sa.Column('user_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'my_professions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'my_professions', type_='foreignkey')
    op.drop_column('my_professions', 'user_id')
    op.drop_constraint(None, 'my_buildings', type_='foreignkey')
    op.drop_column('my_buildings', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
