"""add join table for professions and missions

Revision ID: 4f8c17eecf9d
Revises: b31816bac136
Create Date: 2025-09-17 20:25:56.155524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f8c17eecf9d'
down_revision: Union[str, Sequence[str], None] = 'b31816bac136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('special_mission_profession',
    sa.Column('special_mission_id', sa.Integer(), nullable=False),
    sa.Column('profession_id', sa.Integer(), nullable=False),
    sa.Column('is_direct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profession_id'], ['professions.id'], ),
    sa.ForeignKeyConstraint(['special_mission_id'], ['special_missions.id'], ),
    sa.PrimaryKeyConstraint('special_mission_id', 'profession_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('special_mission_profession')
    # ### end Alembic commands ###
