"""remove unique constraint for saved buildings and professions

Revision ID: 90599b057497
Revises: 0505fca554d7
Create Date: 2025-07-21 00:27:53.699955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90599b057497'
down_revision: Union[str, Sequence[str], None] = '0505fca554d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('my_buildings_building_id_key'), 'my_buildings', type_='unique')
    op.drop_constraint(op.f('uix_profession_id'), 'my_professions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uix_profession_id'), 'my_professions', ['profession_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('my_buildings_building_id_key'), 'my_buildings', ['building_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
