[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pixel_people_optimizer"
version = "0.1.0"
description = "Your project description"
dependencies = []
